import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { EncryptedPayload } from "../types.js";

export const KEY_LENGTH = 32;
export const IV_LENGTH = 12;
export const TAG_LENGTH = 16;
export const KEY_FILE = ".confseal.key";
export const KEY_ENV_VAR = "CONFSEAL_KEY";

const ALGORITHM = "aes-256-gcm";

/**
 * Generates a cryptographically secure 256-bit key.
 * The returned string is the raw 32-byte key encoded as base64.
 */
export function generateKey(): string {
  return randomBytes(KEY_LENGTH).toString("base64");
}

/** Decodes a base64 key string into a Buffer, validating its length. */
export function keyToBuffer(key: string): Buffer {
  let buffer: Buffer;
  try {
    buffer = Buffer.from(key, "base64");
  } catch {
    throw new Error(
      `The ${KEY_ENV_VAR} value could not be decoded. It must be base64-encoded.`,
    );
  }
  if (buffer.length !== KEY_LENGTH) {
    throw new Error(
      `Invalid key length: expected 32 bytes, got ${buffer.length}. ` +
        `Use 'confseal init' to generate a fresh key.`,
    );
  }
  return buffer;
}

/** Encrypts plaintext and returns a base64 payload of iv + auth tag + ciphertext. */
export function encrypt(plaintext: string, key: string): string {
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, keyToBuffer(key), iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return payloadToBase64({ iv, tag, ciphertext });
}

/**
 * Decrypts a payload produced by {@link encrypt}.
 * Throws an actionable error if the payload is malformed, tampered with,
 * or was encrypted with a different key.
 */
export function decrypt(payload: string, key: string): string {
  const decoded = payloadFromBase64(payload);
  const decipher = createDecipheriv(ALGORITHM, keyToBuffer(key), decoded.iv);
  decipher.setAuthTag(decoded.tag);
  try {
    const plaintext = Buffer.concat([
      decipher.update(decoded.ciphertext),
      decipher.final(),
    ]);
    return plaintext.toString("utf8");
  } catch {
    throw new Error(
      "Decryption failed. The payload is corrupted, was tampered with, " +
        "or the wrong key was used.",
    );
  }
}

/** Locates the encryption key from the environment or the key file. */
export function loadKey(projectRoot = process.cwd()): string {
  const fromEnv = process.env[KEY_ENV_VAR];
  if (fromEnv) {
    keyToBuffer(fromEnv); // validate early
    return fromEnv;
  }

  const keyFilePath = join(projectRoot, KEY_FILE);
  if (existsSync(keyFilePath)) {
    const fromFile = readFileSync(keyFilePath, "utf8").trim();
    keyToBuffer(fromFile); // validate early
    return fromFile;
  }

  throw new Error(
    `No encryption key found.\n\n` +
      `Set the ${KEY_ENV_VAR} environment variable:\n` +
      `  export ${KEY_ENV_VAR}="$(cat .confseal.key)"\n\n` +
      `Or place the key in ${KEY_FILE} at the project root (generated by 'confseal init').`,
  );
}

function payloadToBase64(payload: EncryptedPayload): string {
  return Buffer.concat([payload.iv, payload.tag, payload.ciphertext]).toString("base64");
}

function payloadFromBase64(payload: string): EncryptedPayload {
  if (!/^[A-Za-z0-9+/]*={0,2}$/.test(payload) || payload.length % 4 !== 0) {
    throw new Error("The encrypted payload is not valid base64.");
  }

  const buffer = Buffer.from(payload, "base64");

  const minimumLength = IV_LENGTH + TAG_LENGTH;
  if (buffer.length < minimumLength) {
    throw new Error(
      `The encrypted payload is malformed (too short to contain an IV and auth tag).`,
    );
  }

  const iv = buffer.subarray(0, IV_LENGTH);
  const tag = buffer.subarray(IV_LENGTH, minimumLength);
  const ciphertext = buffer.subarray(minimumLength);
  return { iv, tag, ciphertext };
}